/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinates { 'lat' : number, 'long' : number }
export interface Event {
  'creator' : Principal,
  'description' : string,
  'timestamp' : Time,
  'courseName' : string,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'female' : null } |
  { 'male' : null } |
  { 'couple' : null };
export interface Message {
  'content' : string,
  'read' : boolean,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export type Preference = { 'pleasure' : null } |
  { 'romantic' : null } |
  { 'business' : null } |
  { 'casual' : null };
export interface Promise {
  'isLocal' : boolean,
  'name' : string,
  'website' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'lookingFor' : Gender,
  'preference' : Preference,
  'genderPreference' : Gender,
  'gender' : Gender,
  'handicap' : bigint,
  'location' : Coordinates,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<[string, string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRsvp' : ActorMethod<[bigint], undefined>,
  'createEvent' : ActorMethod<[string, string], undefined>,
  'getAllEvents' : ActorMethod<[], Array<[Event, Array<Principal>]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseDirectory' : ActorMethod<[], Array<[string, Promise]>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getSponsors' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[Principal, Time], undefined>,
  'rsvpToEvent' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMatches' : ActorMethod<[], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];