/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Event = IDL.Record({
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
  'courseName' : IDL.Text,
});
export const Gender = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'couple' : IDL.Null,
});
export const Preference = IDL.Variant({
  'pleasure' : IDL.Null,
  'romantic' : IDL.Null,
  'business' : IDL.Null,
  'casual' : IDL.Null,
});
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'long' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'lookingFor' : Gender,
  'preference' : Preference,
  'genderPreference' : Gender,
  'gender' : Gender,
  'handicap' : IDL.Nat,
  'location' : Coordinates,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Promise = IDL.Record({
  'isLocal' : IDL.Bool,
  'name' : IDL.Text,
  'website' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRsvp' : IDL.Func([IDL.Nat], [], []),
  'createEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllEvents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Event, IDL.Vec(IDL.Principal)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseDirectory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Promise))],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getSponsors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Principal, Time], [], []),
  'rsvpToEvent' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMatches' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Event = IDL.Record({
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
    'courseName' : IDL.Text,
  });
  const Gender = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'couple' : IDL.Null,
  });
  const Preference = IDL.Variant({
    'pleasure' : IDL.Null,
    'romantic' : IDL.Null,
    'business' : IDL.Null,
    'casual' : IDL.Null,
  });
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'long' : IDL.Float64 });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'lookingFor' : Gender,
    'preference' : Preference,
    'genderPreference' : Gender,
    'gender' : Gender,
    'handicap' : IDL.Nat,
    'location' : Coordinates,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Promise = IDL.Record({
    'isLocal' : IDL.Bool,
    'name' : IDL.Text,
    'website' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRsvp' : IDL.Func([IDL.Nat], [], []),
    'createEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllEvents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Event, IDL.Vec(IDL.Principal)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseDirectory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Promise))],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getSponsors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Principal, Time], [], []),
    'rsvpToEvent' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMatches' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };